---
title: "CCA"
author: "M. Florencia Miguel"
date: "14 de junio de 2017"
output: html_document
---

```{r initialize, message= FALSE, warning=FALSE}

require(ggplot2)
require(GGally)
require(CCA)

```


```{r data frame, echo= TRUE, message= TRUE, warning= TRUE}

#the canonical.correlations.csv (can) includes trees with and without frugivore interactions. Instead, the selected_trees.csv (cans) only includes trees with frugivore visits. We used this matrix to run CCA.

#can<- read.csv("../data/canonical.correlations.csv",header=T,sep=",",dec=".",na.strings="NA")
#str(can)

cans<- read.csv("../data/selected_trees.csv",header=T,sep=",",dec=".",na.strings="NA")
str(cans)

```


```{r microhabitat variables, echo= TRUE, message= TRUE, warning= TRUE}

#1 to 120 grazed sites, 121 to 190 ungrazed sites
#to grazed sites eliminate ctenomys fru <- can [1:120, 59:70] fru <- fru[,-10]
#to ungrazed sites do not consider data of Bos taurus and Equus caballus 
#vistis 31:42; fruits consumed 43:54; total effect 59:70

#Grazed sites

#fruG <- can [1:120, 31:42]
#fruG <- fruG [, -10]
#plantG <- can [1:120, 4:21]

#Ungrazed sites

#fruUG <- can [121:190, 31:40]
#plantUG <- can [121:190, 4:21]

#To run CCA only considering visited trees 
#Grazed sites

fruG <- cans [1:108, 31:42]
fruG <- fruG [, -10] #I do not include data of Ctenomys mendocinus in grazed sites, because it did not interact with trees
#plantG <- cans [1:108, 4:21]
plantG <- cans [1:108, 4:28]
plantG <- plantG [, -19]
plantG <- plantG [, -19]
plantG <- plantG [, -20]


#Ungrazed sites

fruUG <- cans [109:172, 31:40] #I do not include in analysis data of Bos taurus and Equus caballus for ungrazed land uses
#plantUG <- cans [109:172, 4:21]
plantUG <- cans [109:172, 4:28]
plantUG <- plantUG [, -19]
plantUG <- plantUG [, -19]
plantUG <- plantUG [, -20]




```


```{r correlations, echo= TRUE, message= TRUE, warning= TRUE}

#we’ll look at the correlations within and between the two sets of variables using the matcor function from the CCA package.
#http://www.statisticssolutions.com/table-of-critical-values-pearson-correlation/

matcor(fruG, plantG)

matcor(fruUG, plantUG)

```

```{r corr coefficients, echo= TRUE, message= TRUE, warning= TRUE}

#The function cc performs Canonical Correlation Analysis to highlight correlations between the two data sets
# The canonical squared correlation coefficients represent the proportion of the total variance explained by each pair of canonical variables. 
##Grazed sites
ccG<-cc(fruG, plantG)
ccG

##Ungrazed sites
ccUG<-cc(fruUG, plantUG)
ccUG

```

```{r cca cancor, echo= TRUE, message= FALSE, warning= TRUE}
library(candisc)
cc <- cancor(fruG, plantG)
cc
#Wilks(cc)

ccR <- cancor(fruUG, plantUG)
ccR
#Wilks(ccR)

#plot(cc)
#plot(ccR)


```

```{r WilksL test Grazed sites, echo= TRUE, message= TRUE, warning= TRUE}

#Grazed sites
# tests for canonical variables significancy, the Wilks lambda represents the total variance not explained by the full canonical model. Is  a Test of Significance of the canonical correlation coefficient.
#I adapted the code obtained from https://stats.idre.ucla.edu/r/dae/canonical-correlation-analysis/ (UCLA Statistical Consulting Group, UCLA= University of California in Los Ángeles)

ev <- (1 - ccG$cor^2)

n <- dim(fruG)[1]
p <- length(fruG)
q <- length(plantG)
k <- min(p, q)
m <- n - 3/2 - (p + q)/2

w <- rev(cumprod(rev(ev)))

# initialize
d1 <- d2 <- f <- vector("numeric", k)

for (i in 1:k) {
    s <- sqrt((p^2 * q^2 - 4)/(p^2 + q^2 - 5))
    si <- 1/s
    d1[i] <- p * q
    d2[i] <- m * s - p * q/2 + 1
    r <- (1 - w[i]^si)/w[i]^si
    f[i] <- r * d2[i]/d1[i]
    p <- p - 1
    q <- q - 1
}

pv <- pf(f, d1, d2, lower.tail = F, log.p=F)
(dmat <- cbind(WilksL = w, F = f, df1 = d1, df2 = d2, p = pv))


```



```{r WilksL test Ungrazed sites, echo= TRUE, message= TRUE, warning= TRUE}

#Ungrazed sites
# tests for canonical variables significancy, the Wilks lambda represents the total variance not explained by the full canonical model. Is  a Test of Significance of the canonical correlation coefficient.

ev <- (1 - ccUG$cor^2)

n <- dim(fruUG)[1]
p <- length(fruUG)
q <- length(plantUG)
k <- min(p, q)
m <- n - 3/2 - (p + q)/2

w <- rev(cumprod(rev(ev)))

# initialize
d1 <- d2 <- f <- vector("numeric", k)

for (i in 1:k) {
    s <- sqrt((p^2 * q^2 - 4)/(p^2 + q^2 - 5))
    si <- 1/s
    d1[i] <- p * q
    d2[i] <- m * s - p * q/2 + 1
    r <- (1 - w[i]^si)/w[i]^si
    f[i] <- r * d2[i]/d1[i]
    p <- p - 1
    q <- q - 1
}

pv <- pf(f, d1, d2, lower.tail = FALSE)
(dmat <- cbind(WilksL = w, F = f, df1 = d1, df2 = d2, p = pv))


```
The lambda value represents the total variance not explained by the full canonical model. So, 1- lambda represents the total variance of original variables explained by the canonical function.   

```{r standardized Grazed sites, echo= TRUE, message= TRUE, warning= TRUE}

# standardized fru canonical coefficients diagonal matrix of fru sd's.
# Standardized coefficients represents the weight of the measured variables in producing canonical variables scores. 

s1 <- diag(sqrt(diag(cov(fruG))))
s1 %*% ccG$xcoef

# standardized plant canonical coefficients diagonal matrix of plant sd's

s2 <- diag(sqrt(diag(cov(plantG))))
s2 %*% ccG$ycoef

```

```{r standardized Ungrazed sites, echo= TRUE, message= TRUE, warning= TRUE}

# standardized fru canonical coefficients diagonal matrix of fru sd's
# Standardized coefficients represents the weight of the measured variables in producing canonical variables scores.

s1 <- diag(sqrt(diag(cov(fruUG))))
s1 %*% ccUG$xcoef

# standardized plant canonical coefficients diagonal matrix of plant sd's
s2 <- diag(sqrt(diag(cov(plantUG))))
s2 %*% ccUG$ycoef


```

```{r biplot Grazed sites, echo= TRUE, message= TRUE, warning= TRUE, fig.width=11}

plt.cc (ccG, d1 = 1, d2= 2, int = 1, type = "v", ind.names = NULL,
var.label = TRUE, Xnames = NULL, Ynames = NULL)


```

```{r biplot Ungrazed sites, echo= TRUE, message= TRUE, warning= TRUE, fig.width= 11}

plt.cc (ccUG, d1 = 1, d2 = 2, int = 1, type = "v", ind.names = NULL,
var.label = TRUE, Xnames = NULL, Ynames = NULL)

```


```{r mesohabitat variables, echo= TRUE, message= TRUE, warning= TRUE}

#1 to 120 grazed sites, 121 to 190 ungrazed sites
#to grazed sites eliminate ctenomys fru <- can [1:120, 59:70] fru <- fru[,-10]
##to ungrazed sites eliminate ctenomys (when using the total effect) fru <- can [121:190, 60:69], fru <- fru[,-9]
#vistis 31:42; fruits consumed 43:54; total effect 59:70


#To run CCA only considering visited trees 
#Grazed sites

#fruGh <- cans [1:108, 31:42]
#fruGh <- fruGh [, -10]
plantGh <- cans [1:108, 24:30]
plantGh <- plantGh [, -2]

#Ungrazed sites

#fruUGh <- cans [109:172, 31:40]
plantUGh <- cans [109:172, 24:30]
plantUGh <- plantUGh [, -2]

```

```{r mesohabitat correlations, echo= TRUE, message= TRUE, warning= TRUE}

#we’ll look at the correlations within and between the two sets of variables using the matcor function from the CCA package.

matcor(fruG, plantGh)

matcor(fruUG, plantUGh)
```


```{r mesohabitat corr coefficients, echo= TRUE, message= TRUE, warning= TRUE}

#The function cc performs Canonical Correlation Analysis to highlight correlations between the two data sets
# The canonical squared correlation coefficients represent the proportion of the total variance explained by each pair of canonical variables. 
##Grazed sites
ccGh<-cc(fruG,plantGh)
ccGh

##Ungrazed sites
ccUGh<-cc(fruUG,plantUGh)
ccUGh

```

```{r mesohabitat cca cancor, echo= TRUE, message= TRUE, warning= TRUE}
library(candisc)
cch <- cancor(fruG,plantGh)
cch
#Wilks(cc)

ccRh <- cancor(fruUG, plantUGh)
ccRh
#Wilks(ccR)

#plot(cc)
#plot(ccR)

```

```{r mesohabitat WilksL test Grazed sites, echo= TRUE, message= TRUE, warning= TRUE}

#Grazed sites
# tests for canonical variables significancy, the Wilks lambda represents the total variance not explained by the full canonical model. Is  a Test of Significance of the canonical correlation coefficient.
#I adapted the code obtained from https://stats.idre.ucla.edu/r/dae/canonical-correlation-analysis/ (UCLA Statistical Consulting Group, UCLA= University of California in Los Ángeles)

ev <- (1 - ccGh$cor^2)

n <- dim(fruG)[1]
p <- length(fruG)
q <- length(plantGh)
k <- min(p, q)
m <- n - 3/2 - (p + q)/2

w <- rev(cumprod(rev(ev)))

# initialize
d1 <- d2 <- f <- vector("numeric", k)

for (i in 1:k) {
    s <- sqrt((p^2 * q^2 - 4)/(p^2 + q^2 - 5))
    si <- 1/s
    d1[i] <- p * q
    d2[i] <- m * s - p * q/2 + 1
    r <- (1 - w[i]^si)/w[i]^si
    f[i] <- r * d2[i]/d1[i]
    p <- p - 1
    q <- q - 1
}

pv <- pf(f, d1, d2, lower.tail = F, log.p=F)
(dmat <- cbind(WilksL = w, F = f, df1 = d1, df2 = d2, p = pv))

```

```{r mesohabitat WilksL test Ungrazed sites, echo= TRUE, message= TRUE, warning= TRUE}

#Grazed sites
# tests for canonical variables significancy, the Wilks lambda represents the total variance not explained by the full canonical model. Is  a Test of Significance of the canonical correlation coefficient.
#I adapted the code obtained from https://stats.idre.ucla.edu/r/dae/canonical-correlation-analysis/ (UCLA Statistical Consulting Group, UCLA= University of California in Los Ángeles)

ev <- (1 - ccUGh$cor^2)

n <- dim(fruUG)[1]
p <- length(fruUG)
q <- length(plantUGh)
k <- min(p, q)
m <- n - 3/2 - (p + q)/2

w <- rev(cumprod(rev(ev)))

# initialize
d1 <- d2 <- f <- vector("numeric", k)

for (i in 1:k) {
    s <- sqrt((p^2 * q^2 - 4)/(p^2 + q^2 - 5))
    si <- 1/s
    d1[i] <- p * q
    d2[i] <- m * s - p * q/2 + 1
    r <- (1 - w[i]^si)/w[i]^si
    f[i] <- r * d2[i]/d1[i]
    p <- p - 1
    q <- q - 1
}

pv <- pf(f, d1, d2, lower.tail = F, log.p=F)
(dmat <- cbind(WilksL = w, F = f, df1 = d1, df2 = d2, p = pv))

```

```{r biplot mesohabitat Grazed sites, echo= TRUE, message= TRUE, warning= TRUE, fig.width= 11}

plt.cc (ccGh, d1 = 1, d2= 2, int = 1, type = "v", ind.names = NULL,
var.label = TRUE, Xnames = NULL, Ynames = NULL)


```

```{r biplot mesohabitat Ungrazed sites, echo= TRUE, message= TRUE, warning= TRUE, fig.width= 11}

plt.cc (ccUGh, d1 = 1, d2 = 2, int = 1, type = "v", ind.names = NULL,
var.label = TRUE, Xnames = NULL, Ynames = NULL)

```
